### ISSUE TITLE
A question about the ONNG paper

### ISSUE THREAD

**Issue by coraler** [yahoojapan/NGT#101]
Your work was great and I learned a lot！
When reading ONNG paper, the value of e_o used by algorithm 3 when calling algorithm 2 is 0, can you explain the reason? Wouldn't algorithm 2 never enter the loop, or should it be e_o?
It would be a great help if you could answer this question,thanks!

**Comment by masajiro** [comment]
Thank you for your interest in NGT.
0 of ConstructAdjustedGraph(G, 0, e) In Algorithm 3 is to build TKNNG that is a transposed graph of KNNG, and there is a mistake In Algorithm 2.

5: while S ≠  ∅ and p ≤ e<sub>o</sub> and p ≤ e<sub>i</sub>
&rarr;
5: while S ≠ ∅ and (p ≤ e<sub>o</sub> or p ≤ e<sub>i</sub>)
