### ISSUE TITLE
While following the installtion setup for mac os I recieved this error

### ISSUE THREAD

**Issue by saurabhkumar8112** [yahoojapan/NGT#108]
After i ran
```unzip NGT-x.x.x.zip```
I got this error
```cannot find or open NGT-x.x.x.zip, NGT-x.x.x.zip.zip or NGT-x.x.x.zip.ZIP```
Does x.x.x. have to replaced by some placeholder? if yes, what it is or how to find it.

**Comment by masajiro** [comment]
First, download the zip file from [the latest NGT release](https://github.com/yahoojapan/NGT/releases/tag/v1.13.7). Then, run [the instructions](https://github.com/yahoojapan/NGT#on-macos-using-homebrew) replaced NGT-x.x.x.zip with the downloaded zip file name.
