### ISSUE TITLE
python sample code cannot pass

### ISSUE THREAD

**Issue by o0fatigue** [yahoojapan/NGT#11]
I have installed both base and python packages successfully. However, when I try to run the sample code in python/README.md, it throws error as below:

```
Traceback (most recent call last):
  File "ngt_sample.py", line 11, in <module>
    index = ngt.Index.create("tmp", dim)
  File "/root/workspace/NGT-1.3.1/python/ngt/base.py", line 250, in create
    index = Index.__ngt.ngt_create_graph_and_tree(path, prop, err)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

Since this sample code does not work, I cannot find out how to use NGT to create an index...

**Comment by o0fatigue** [comment]
Solved. Path argument should be b"tmp" instead of "tmp".

**Comment by AshwatKumar** [comment]
How did you resolve this issue ?
I am getting this same error. Please help urgently

**Comment by o0fatigue** [comment]
> How did you resolve this issue ?
> I am getting this same error. Please help urgently

```
index = ngt.Index.create("tmp", dim)
```
This should be 
```
index = ngt.Index.create(b"tmp", dim)
```

According to my memory, this fixed the error in my case.
