### ISSUE TITLE
I got Runtime error: src/ngtpy.cpp

### ISSUE THREAD

**Issue by btlam87** [yahoojapan/NGT#112]
Hi there!
I used NGT for 2 years and this is the first time i get this error when add vectors to NGT tree. It happend when code hit .batch_insert().
My enviroment is: ubuntu 18.04, python 3.6, NGT-1.11.6.

I dont know how to solve it, pleas help me!

**Comment by masajiro** [comment]
I cannot find any runtime error in [the line](https://github.com/yahoojapan/NGT/blob/b9f8c37d916d7319f4032d1b68ba7601dc755895/python/src/ngtpy.cpp#L112) you specified. Could you tell me what the runtime error message is?

**Comment by btlam87** [comment]
Thanks for your return. It not show me any message but "Runtime Error: src/ngtpy.cpp" , when i try catch the .batch_insert() function it show me that again.
When i searched for "src/ngtpy.cpp" on code i found 2 line in setup.py.

![Screenshot from 2022-02-24 09-01-33](https://user-images.githubusercontent.com/56066704/155443686-4c6d6475-1ecc-456f-b326-cb9ea9d5dfaf.png)

**Comment by masajiro** [comment]
I cannot reproduce the error you mentioned on ubuntu 18.04 with python 3.6 and NGT 1.11.6 from build or pypi. Could you run [sample.py](https://github.com/yahoojapan/NGT/blob/master/python/sample/sample.py) including batch_insert() and check the result?

**Comment by btlam87** [comment]
I tried sample.py and it working good. I think it because eviroment of container. It happend when i build a new container to run NGT then i fixed now by copy NGT things from my old container and past to new one. After restart the new container it worked. So
