### ISSUE TITLE
Optimizer: "Cannot optimize the number of edges"

### ISSUE THREAD

**Issue by fonspa** [yahoojapan/NGT#113]
Hi,
I'm trying to use the Optimizer class in the Python binding, for a version of NGT which I built from sources (v1.14.1) but I encounter a bug which seems to be an off-by-one error.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_28461/550346330.py in <module>
      1 optimizer = ngtpy.Optimizer(log_disabled = True)
----> 2 optimizer.optimize_number_of_edges_for_anng(os.path.join(export_path, "ngt-opt"))

RuntimeError: /usr/local/include/NGT/GraphOptimizer.h:505: Optimizer::optimizeNumberOfEdgesForANNG: Cannot optimize the number of edges. 0:0.937933 # of objects=5676310
```

The dataset I use has 5676309 data points, and the GraphOptimizer seems to want to work on point 5676310.

Minimal code to reproduce:
```
ngtpy.create(os.path.join(export_path, "opt"), 128, distance_type='L2', object_type='Float16')
index = ngtpy.Index(path=os.path.join(export_path, "opt"), read_only=False, zero_based_numbering=True, log_disabled=False)

for vec in xb:
    index.insert(vec)
index.save()
index.close()

optimizer = ngtpy.Optimizer(log_disabled = True)
optimizer.optimize_number_of_edges_for_anng(os.path.join(export_path, "opt"))
```

Am I doing something wrong here ?  
Thank you !

**Comment by masajiro** [comment]
Since the message shows the number of inserted objects + 1 by mistake, I don't think that it is an off-by-one error. When you specify 'Float' to the object type, do you get the same error?

**Comment by fonspa** [comment]
Good call, in 'Float' there's no error and the optimization process seems to work fine.

So there's a problem with fp16 and the Optimizer ?  
Concerning the fp16, according to your experience, is there a tangible benefit in terms of performances to work in fp16 instead of fp32 ?  
I didn't encounter yet a database where fp16 was faster than fp32.

Thank you very much for your help and your time!

**Comment by fonspa** [comment]
Hi, that's great, thank you for working on a fix! I will test again when it's released.

I built the NGT libraries from sources (on a CPU with AVX2) and built the python bindings from the `python/` directory, by following the wiki, I believe I should get the benefits of AVX2 extensions even when building an index from Python code.

**Comment by masajiro** [comment]
I have just made a new release v1.14.2 with bug fixes of the optimizer relating to FP16.

**Comment by masajiro** [comment]
I closed this issue for now. Feel free to reopen this whenever you find any issue.
