### ISSUE TITLE
Is there an interface that supports returning the number of vectors？

### ISSUE THREAD

**Issue by lefeiwang** [yahoojapan/NGT#122]

**Comment by lefeiwang** [comment]
> For C++, [getNumberOfIndexedObjects](https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Index.h#L446) is the function to get the number of the indexed vectors. [get_num_of_objects](https://github.com/yahoojapan/NGT/blob/master/python/README-ngtpy.md#get_num_of_objects) is for python.

Is there an interface for golang calls?

**Comment by masajiro** [comment]
There is no interface for golang. However, I can provide the C API instead of that, if it is helpful.

**Comment by lefeiwang** [comment]
> There is no interface for golang. However, I can provide the C API instead of that, if it is helpful.

The C interface can also be called by myself.  thanks！！！

**Comment by lefeiwang** [comment]
> There is no interface for golang. However, I can provide the C API instead of that, if it is helpful.

**Comment by lefeiwang** [comment]
> There is no interface for golang. However, I can provide the C API instead of that, if it is helpful.

If you have time, please help provide the C API.

**Comment by masajiro** [comment]
I have released NGT v1.14.8 with the [interface](https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Capi.h#L219) that you requested.

**Comment by lefeiwang** [comment]
> I have released NGT v1.14.8 with the [interface](https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Capi.h#L219) that you requested.

Problem solved, thank you very much.
