### ISSUE TITLE
Non-similar length vectors?

### ISSUE THREAD

**Issue by Hadryan** [yahoojapan/NGT#128]
How to search on Arbitrary length vectors?
e.g.:

{1, 0, ..., 1.32} [500 dimensions]
{4, 1, ..., 6.12} [503 dimensions]
...
{0.5, 0.74, ..., 0.2} [501 dimensions]

**Comment by masajiro** [comment]
What is the similarity metric for the vectors?

**Comment by Hadryan** [comment]
Cosine similarity of QG.
However if any other methods support non-similar length vectors, I'd be more than happy to test

**Comment by masajiro** [comment]
My understanding is that the cosine similarity is defined on fixed dimension vectors.  How do you compute the cosine similarity for variable length vectors?
