### ISSUE TITLE
Cannot alloc memory error

### ISSUE THREAD

**Issue by o0fatigue** [yahoojapan/NGT#13]
I was trying to build memory-shared index from 102GB tsv file. However, it came out with the following error. 

The machine I am using has a RAM of 250GB, and I was able to build non-shared version index from 200+GB tsv file before.

It seems that there is a limit of memory size in the memory-shared version?

```
alloc size over. size=1073741824.
Fatal Error: Allocating memory size is too big for this settings.
             Max allocation size should be enlarged.
Aborted (core dumped)
```

**Comment by masajiro** [comment]
You might be trying to handle a huge amount of data beyond our assumption.
Could you tell me the number of the objects, dimensionality and data type for our future improvement?

Although in fact there are parameters to define the maximum memory size that can be allocated at once, they cannot be changed from the outside.
Could you increase these three parameter's default values below?
https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Index.h#L73-L75

**Comment by o0fatigue** [comment]
Thanks a lot for your reply. This helps a lot.

I am processing an index with over 100M objects and 40 dimension.

In addition, I found that NGT_SHARED_MEMORY_MAX_SIZE (default value 1024MB) in defines.h.in should also be changed.

I am trying again with these parameter changes. Since this will cost a few time, I may report the result later. 

Thanks again.

**Comment by masajiro** [comment]
Thank you for your additional information.

NGT_SHARED_MEMORY_MAX_SIZE might also work for this problem.

**Comment by o0fatigue** [comment]
I was able to build index successfully with the settings above. Appreciate your help.
