### ISSUE TITLE
How to reduce grp / objpo / trei / trel files size?

### ISSUE THREAD

**Issue by netdur** [yahoojapan/NGT#131]
Currently each file is ~11 GB in size, my data set is around 100 records, my configuration as following

```
NGT::Property property;
property.dimension = 512;
property.objectType = NGT::Index::Property::ObjectType::Float;
property.distanceType = NGT::Index::Property::DistanceType::DistanceTypeCosine;
property.indexType = NGT::Index::Property::GraphAndTree;

NGT::Index::create(indexName, property);
```

thank you

**Comment by masajiro** [comment]
You can change the sizes of the files like [this](https://github.com/yahoojapan/NGT/blob/main/lib/NGT/Command.cpp#L170-L172). The parameters limit the maximum number of stored vectors. You can store up to about 50M vectors for every 512. However, the maximum size also depends on the number of dimensions.

**Comment by netdur** [comment]
thank you sir
