### ISSUE TITLE
Specify num_threads for searching

### ISSUE THREAD

**Issue by Charlyo** [yahoojapan/NGT#133]
Dear developers!

Thank for all the work done in NGT.

Is there any way to also limit the number of threads for search?

**Comment by masajiro** [comment]
NGT uses just one thread for each one query. Does this answer your question?

**Comment by Charlyo** [comment]
By default, there's a ThreadPool created of 32 threads. It would be nice to be able to change this value in python.

**Comment by masajiro** [comment]
[ThreadPool](https://github.com/yahoojapan/NGT/blob/979a9af8310d19e2a5b9a0c7b66cba6f116c25bf/lib/NGT/Thread.h#L86) is used only for building an index. You can specified the size in these methods:  [batch_insert](https://github.com/yahoojapan/NGT/blob/main/python/README-ngtpy.md#batch_insert), [build_index](https://github.com/yahoojapan/NGT/blob/main/python/README-ngtpy.md#build_index).
