### ISSUE TITLE
Is there any benchmark result for NGT QG/QBG?

### ISSUE THREAD

**Issue by xiaofan-luan** [yahoojapan/NGT#139]
Hi Team,
Thanks for the great work on quantinized graph.
I wonder is there benchmark result for quantized graph  build? Since build speed is also very important on production use cases

**Comment by masajiro** [comment]
For QB build times, [ANN Benchmarks](https://ann-benchmarks.com/index.html) is a useful reference. Each dataset page contains various evaluation results like [this](https://ann-benchmarks.com/glove-100-angular_10_angular.html).

**Comment by xiaofan-luan** [comment]
Thanks for the reply.
NGT seems not listed in GIST and some other dataset. Is there any advice on improving NGT index build speed? This is also very important for real world production

**Comment by masajiro** [comment]
In general, there is a trade-off between build time and performance. For NGT, its build time can be reduced by changing parameters, but performance is also reduced. On the other hand, since NGT supports multi-threading for building the index, multi-core can significantly reduce the build time.

**Comment by xiaofan-luan** [comment]
Thanks for the clarifiction. Great work, will do more benchmark on it
