### ISSUE TITLE
How to update NGT from older version to new one?

### ISSUE THREAD

**Issue by frederic89** [yahoojapan/NGT#147]
If I compile to setup from binary file download from releases, how can I update NGT from older version to new one?
First uninstall, or override in /usr/local/bin/ngt?

**Comment by masajiro** [comment]
You do not need to uninstall NGT. All you need to do is reinstall NGT (`make install`).

**Comment by frederic89** [comment]
> You do not need to uninstall NGT. All you need to do is reinstall NGT (`make install`).

Thanks
