### ISSUE TITLE
Quantization in qg-l2-float.cpp

### ISSUE THREAD

**Issue by MINGRUI001** [yahoojapan/NGT#153]
For the sample of qg-l2-float, it shall be to construct a quantization graph and search on it. However, in the searching part (index.search(sc), line 99 of qg-l2-float.cpp), it is still to search the original graph without considering the quantization codes. I have also checked that some PQ-related functions, e.g.,  createDistanceLookup, are not called. Isn't it? Thanks.

**Comment by masajiro** [comment]
Thank you for your investigation. I have released [v2.1.4](https://github.com/yahoojapan/NGT/releases/tag/v2.1.4) which resolves this issue.
