### ISSUE TITLE
I use the following s3 protocol API environment variables to start the Milvus service, is it correct?

### ISSUE THREAD

**Issue by a28124791** [yahoojapan/NGT#169]
I use the following s3 protocol API environment variables to start the Milvus service, is it correct?
我使用下面的s3协议接口环境变量启动Milvus服务，是否正确？
docker run -d -it \
  --name milvus_datacoord-up1 \
  -p 13333:13333 \
  -e "ETCD_ENDPOINTS=192.168.95.200:12379" \
  -e "ETCD_ROOTPATH=gbotby" \
  -e "ETCD_METASUBPATH=meta" \
  -e "ETCD_KVSUBPATH=kv" \
  -e "AWS_ACCESS_KEY_ID=werwerwer3rwrwrw" \
  -e "AWS_SECRET_ACCESS_KEY=ererer3erererererr" \
  -e "S3_BUCKET_NAME=wordcount" \
  -e "S3_ENDPOINT_URL=http://192.168.195.20:9878" \
  -e "PULSAR_ADDRESS=pulsar://192.168.95.200:6650" \
  -e "DATA_COORD_ADDRESS=192.168.95.200:13333" \
  -e "DATA_COORD_ENABLE_ACTIVE_STANDBY=true" \
milvusdb/milvus milvus run datacoord

**Comment by masajiro** [comment]
Is it possible that you submitted this issue to the wrong repository?
