### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by AshwatKumar** [yahoojapan/NGT#26]
I am following 'ngpy' tutorial , here https://github.com/yahoojapan/NGT/tree/master/python 
under simple samples , ngpy section.
I am executing this line 'ngtpy.create(b"tmp", dim)' 
I am getting this error.
Can you explain, what 'tmp' is? Is it a directory or file or what? 
Why have we put 'b' infront of it?

OS - Ubuntu 16 
Python Version - Python 3.5

**Comment by masajiro** [comment]
What error did you get?
Did you use pip to install ngtpy?
tmp is the name of the created index directory. It makes 'tmp' in the working directory.
b is not always necessary.

**Comment by masajiro** [comment]
If your cpu cannot use avx2, you might get the error message.
Could you install NGT from source codes using cmake as follows.
```
cmake -DNGT_AVX_DISABLED=ON ..
```
Or, please use cpu with avx2.
tmp is the name of the created index directory. It makes 'tmp' in the working directory.
b is not always necessary.
