### ISSUE TITLE
About onng

### ISSUE THREAD

**Issue by MrHwc** [yahoojapan/NGT#30]
Is NGT only able to implement the onng algorithm via the ngt command? How does ngtpy implement onng algorithm? Ann-benchmarks seems to be the onng algorithm implemented by the ngt command.

**Comment by masajiro** [comment]
I have just released NGT v1.7.7 that includes the graph reconstruction function (Optimizer) for ngtpy. However, it does not include any manual of it yet. Now I am just writing manuals about it. Here is a brief example.
```
# ngt reconstruct-graph -m S -o 10 -i 120 anng_path onng_path                                                                          
optimizer = ngtpy.Optimizer()
optimizer.set(num_of_outgoings = 10, num_of_incomings = 120)
optimizer.execute(anng_path, onng_path)
```
[Optimizer](https://github.com/yahoojapan/NGT/blob/master/python/src/ngtpy.cpp#L464-L481) will also help you.

**Comment by MrHwc** [comment]
@masajiro thank you! I separated a small dataset of 10000 in gist1m. I built an empty index, adding 100 vectors to it, up to 10,000 each time. I set the query to return 100 neighbors, but only 42 neighbors were returned during the test. When I test in gist1m, I can return 100 neighbors normally. Is the data set of 10000 too small?

**Comment by masajiro** [comment]
It is not too small. Before calling the optimizer, could you check if you can get 100 neighbors?

**Comment by masajiro** [comment]
Here is the [Optimizer reference](https://github.com/yahoojapan/NGT/blob/master/python/README-ngtpy.md#class-optimizer) to construct ONNG.
