### ISSUE TITLE
Parameter Tuning (Perf & Recall)

### ISSUE THREAD

**Issue by tanliboy** [yahoojapan/NGT#33]
I explored NGT with some real dataset (100K 129d normalized vectors, top 100, 10 queries) with default parameters used in `Command.cpp` as below. I turned on `AVX`, `OpenMP` and `opt` optimization using GCC, but I didn't use `NGT_SHARED_MEMORY_ALLOCATOR` setting to keep the index in memory.

```
  NGT::Property prop;
  prop.edgeSizeForCreation = 10;
  prop.edgeSizeForSearch = 40;
  prop.batchSizeForCreation = 200;
  prop.insertionRadiusCoefficient = 1.1;
  prop.truncationThreshold = 0;
  prop.dimension = transDimension;;
  prop.threadPoolSize = 24;
  prop.pathAdjustmentInterval = 0;
  prop.dynamicEdgeSizeBase = 30;
  prop.buildTimeLimit = 0.0;
  prop.distanceType = NGT::Index::Property::DistanceType::DistanceTypeNormalizedCosine;

  NGT::GraphAndTreeIndex index(prop);
  index.append(transData.data(), dataSize);
  index.createIndex(24);

  vector<int64_t> outputIndexes(queryDataSize * k);

  for (size_t i = 0; i < queryDataSize; i++) {
    NGT::Object *query = index.allocateObject(
        transQueryData.data() + i * transDimension, transDimension);

    NGT::SearchContainer sc(*query);
    NGT::ObjectDistances objects;
    sc.setResults(&objects);
    sc.setSize(k);
    sc.setRadius(FLT_MAX);
    sc.setEpsilon(0.1);

    int64_t startTime = getWallTimeMS();
    index.search(sc);
    int64_t endTime = getWallTimeMS();

    LOG(INFO) << " query " << i
      << ": ts = " << endTime - startTime
      << " ms, # of result = " << objects.size();

    for (size_t j = 0; j < objects.size() && j < k; j++) {
      outputIndexes[i * k + j] = objects[j].id - 1;
    }
    index.deleteObject(query);
  }
```

Here is the test result
```
query 0: ts = 93 ms, # of result = 100
query 1: ts = 94 ms, # of result = 100
query 2: ts = 0 ms, # of result = 0
query 3: ts = 93 ms, # of result = 100
query 4: ts = 0 ms, # of result = 0
query 5: ts = 86 ms, # of result = 100
query 6: ts = 88 ms, # ofl result = 100
query 7: ts = 90 ms, # of result = 100
query 8: ts = 89 ms, # of result = 100
query 9: ts = 89 ms, # of result = 100
```
 There are several issues in this test:
- There is no result for two of ten queries. Did I miss anything in the parameter settings? 
- We need to create `ObjectDistance` for every query. Is there a way that we can reuse the `objects` to avoid allocating memory for wide-range and high-frequency queries?
- The latency is high. As a comparison, it took 26ms in total to calculate ten results using CBLAS+OpenMP brute force matrix multiplication. I tried to tune the `setEpsilon` to be 0.03. It took effect to reduce the latency to half with a sacrifice on recall. However, it is still more than the brutal force on average. Are there other parameters or compilation options that I can try to improve the CPU performance?

Thanks!

**Comment by masajiro** [comment]
> * There is no result for two of ten queries. Did I miss anything in the parameter settings?

I do not have any idea about that at this moment.
```
index.search(sc);
```
Could you exchange the line above for the line below and run again?
```
index.linearSearch(sc);
```
linearSearch just executes linear search without the use of the index. If the result is the same as the previous result, it is caused by invalid queries. If not, no result is caused by the index. 

> * Is there a way that we can reuse the objects to avoid allocating memory for wide-range and high-frequency queries?

You can move the line below to the outside of the for statement.
```
    NGT::ObjectDistances objects;
```
The line below might be needed within the for statement.
```
   objects.clear()
```
> * Are there other parameters or compilation options that I can try to improve the CPU performance?

* You may want to use ONNG as below.
https://github.com/yahoojapan/NGT/tree/master/bin/ngt#onng
* You may want to open the index with a read only flag as below to improve the search performance.
https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Command.cpp#L402

**Comment by tanliboy** [comment]
Thank you, @masajiro! It is very helpful. 

> > * There is no result for two of ten queries. Did I miss anything in the parameter settings?
> 
> I do not have any idea about that at this moment.
> 
> ```
> index.search(sc);
> ```
> 
> Could you exchange the line above for the line below and run again?
> 
> ```
> index.linearSearch(sc);
> ```
> 
> linearSearch just executes linear search without the use of the index. If the result is the same as the previous result, it is caused by invalid queries. If not, no result is caused by the index.
> 

For the first issue, I found it is actually related to invalid query data. Thanks for your suggestions on debugging this situation.

> > * Is there a way that we can reuse the objects to avoid allocating memory for wide-range and high-frequency queries?
> 
> You can move the line below to the outside of the for statement.
> 
> ```
>     NGT::ObjectDistances objects;
> ```
> 
> The line below might be needed within the for statement.
> 
> ```
>    objects.clear()
> ```
> 

I tried with your suggestions. I noticed that `ObjectDistances` inherits from `vector<ObjectDistance>` and clearing the vector incurs additional deallocation cost across all results – it is substantial when we have tens of thousands results. On the other hand, the `ObjectDistance` seems could be reused given it only includes `id` and `distance` pair.

If it is reasonable to you to reuse the `ObjectDistance` for reducing memory cost, I can help with a pull request along the way.

> > * Are there other parameters or compilation options that I can try to improve the CPU performance?
> 
> * You may want to use ONNG as below.
>   https://github.com/yahoojapan/NGT/tree/master/bin/ngt#onng
> * You may want to open the index with a read only flag as below to improve the search performance.
>   https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Command.cpp#L402

I will further explore, thanks.

At the same time, I noticed two small issues:
- The compiling warning: there are some repetitive declarations for variables that shadow variables in the parent scope. It is triggered some GCC warnings in a verbose mode, and it would be great if we could clear up as well.
- I noticed that we use `iostream` to output log outside of the Command file, and I have not found a flag that we can turn off the logging. It lags the perf and seems distracting. Did I miss anything? Or could we add a flag so that we can disable it when needed?

**Comment by masajiro** [comment]
> Did I miss anything? Or could we add a flag so that we can disable it when needed?

There is no flag to turn off the logging. I am going to add a kind of a flag to handle the logging in the near future.

**Comment by masajiro** [comment]
> * I noticed that we use iostream to output log outside of the Command file, and I have not found a flag that we can turn off the logging. It lags the perf and seems distracting. Did I miss anything? Or could we add a flag so that we can disable it when needed?

I have added arguments to [Index](https://github.com/yahoojapan/NGT/blob/v1.7.10/python/README-ngtpy.md#__init__) and [Optimizer](https://github.com/yahoojapan/NGT/blob/v1.7.10/python/README-ngtpy.md#__init__-1) to disable the logging.

**Comment by masajiro** [comment]
> *The compiling warning: there are some repetitive declarations for variables that shadow variables in the parent scope. It is triggered some GCC warnings in a verbose mode, and it would be great if we could clear up as well.

I removed most of the warnings that I found.
