### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [yahoojapan/NGT#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CompactVector:clear](https://github.com/yahoojapan/NGT/blob/985ffad43c8057f37ef95c65caddaf75fe3b9672/lib/NGT/Common.h#L120 "CompactVector::clear function")
- [Index::close](https://github.com/yahoojapan/NGT/blob/985ffad43c8057f37ef95c65caddaf75fe3b9672/lib/NGT/Index.h#L222 "Index::close function")
- [Thread](https://github.com/yahoojapan/NGT/blob/985ffad43c8057f37ef95c65caddaf75fe3b9672/lib/NGT/Thread.cpp#L44 "Destructor for Thread")

**Comment by dmyzk** [comment]
Thank you for your suggestion!

**Comment by elfring** [comment]
Are there [still any update candidates to consider](https://github.com/yahoojapan/NGT/blob/355754a7cd4ad73d959c7ad18966a203db88630d/lib/NGT/Index.h#L259 "Update candidate: Index::close()")?
