### ISSUE TITLE
No module named 'ngtpy'

### ISSUE THREAD

**Issue by GabbySuwichaya** [yahoojapan/NGT#43]
Thanks for releasing NGT. 
I have tried running the provide sample python script. 

It seems that the scripts works as expected (quick and quite accurate) after I create the conda environment for running NGT package. 
However, after I deactivate and activate the same environment again, I get the error message: 

`ModuleNotFoundError: No module named 'ngtpy'`

It seems to be the problem with how the path is specified. 
But, I don't know how to fix this problem. Could you recommend how to fix this path problem, or may be could you give me away to force the path to both ngtpy and ngt modules?  

I performed the following command lines, which leads to the problem:  

1. Firstly, I installed NGT on my linux (base-environment)

  $ unzip NGT-x.x.x.zip
  $ cd NGT-x.x.x
  $ mkdir build
  $ cd build 
  $ cmake ..
  $ make 
  $ make install
  $ ldconfig /usr/local/lib

2. Then, I install the python package in base-environment using: 
 
$ pip3 install pybind11
$ pip3 install numpy
$ cd NGT_ROOT/python
$ python3 setup.py sdist
$ pip3 install dist/ngt-x.x.x.tar.gz
 
3. Then, I create a conda environment, activate it to run the sample.py, and then, deactivate the conda environment. 
4. After deactivation, I just simply activate the conda environment that I have just created. Then, it doesn't work.

**Comment by masajiro** [comment]
It seems that anaconda has python3 but no pip3 in my environment. If your environment is the same as mine, you have may use /usr/bin/pip3 instead of anaconda's pip. It means that ngtpy was installed in the wrong place. Why don't you use "pip" that is placed in anaconda directory instead of "pip3".

**Comment by GabbySuwichaya** [comment]
Yes, it works! You saved my life !  Thanks so much !!!!!

**Comment by ldmtwo** [comment]
@masajiro It would be great if the install/build instructions/readme.md included the latter half of Gabby's steps above. Thanks.

**Comment by masajiro** [comment]
@ldmtwo What is the latter half?

> $ pip3 install pybind11
$ pip3 install numpy
$ cd NGT_ROOT/python
$ python3 setup.py sdist
$ pip3 install dist/ngt-x.x.x.tar.gz

is written in [README.md](https://github.com/yahoojapan/NGT/blob/master/python/README.md#install).
Or my comment?
> It seems that anaconda has python3 but no pip3 in my environment. If your environment is the same as mine, you have may use /usr/bin/pip3 instead of anaconda's pip. It means that ngtpy was installed in the wrong place. Why don't you use "pip" that is placed in anaconda directory instead of "pip3".
