### ISSUE TITLE
Not an issue, just want to say thank you for the brilliant product

### ISSUE THREAD

**Issue by mrjj** [yahoojapan/NGT#45]
This is the first product of this kind that i've got up and running over existing heavyweight VSR dump (multilayer embeddings from image recognition CNN-s). Spent not more than 30 minutes on interface replacement toward NGTd. Now no buggy vendor drivers, kdumps OOMS and other common problems Everything is VERY convinient. (I've used FAISS, Annoy and some in-home Yandex stuff previously)

Algorythmic part is exceptional, especially PQ post-verification trick, finally there is no need to investigate precision problems for cases of irrelevant output and focus on VSR construction logic.

I wish all luch to NGT

**Comment by masajiro** [comment]
Thank you for your compliments. When I find a new issue, I always get a little nervous to imagine how big the issue is. But it was the first time that the issue title encouraged me.
