### ISSUE TITLE
Cosine similarity distance outputs are in ascending order

### ISSUE THREAD

**Issue by dong-hoang** [yahoojapan/NGT#46]
Hi, 
I'm using cosine similarity as the distance metrics. I set output size is 15 and I saw that the distance is increasing. This is confusing me because if the angle between 2 points is very small then their cosine will reach 1. How can I change the arrangement of the output by descending order when using cosine similarity metric ? 
Thanks in advances !
Dong
{
Rank	ID	Name	Distance
1	137	NVH1	0.478774
2	133	NVH2	0.494715
3	136	NVH2	0.498162
4	135	NVH2	0.520622
5	134	NVH2	0.522601
6	138	NVH2	0.536414
7	851	TVX	        0.644147
8	2340 DTV	0.647083
9	3338 HND	0.65958
10	1012 NTH	0.662446
11	1604 HMH	0.66996
12	958	NMN	0.672668
13	3233 NHH	0.676299
14	2611 HMH	0.685966
15	1013 NMJ	0.688811

}

**Comment by masajiro** [comment]
Since cosine similarity is not a distance function, NGT uses __1.0 - cosine similarity__ as a distance function instead of __cosine similarity__. Therefore, actual cosine similarity value is __1.0 - the resultant distance value__.
