### ISSUE TITLE
NGT does not support Python 3.8.x

### ISSUE THREAD

**Issue by Alexander-Kuzmin** [yahoojapan/NGT#49]
I am trying to evaluate NGT library for Python under Mac OS X Catalina 10.15.2 with Visual Studio Code.

1. "pip3 install ngt" does not work for Python 3.8.x
2. for Python version 3.7.5 and below it works

**Comment by masajiro** [comment]
I uploaded NGT v1.8.4 for Python 3.8 on macOS to PyPI.

**Comment by Alexander-Kuzmin** [comment]
It works. Thanks!
