### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [yahoojapan/NGT#5]
I have seen that [no loop is used around a call](https://github.com/yahoojapan/NGT/blob/985ffad43c8057f37ef95c65caddaf75fe3b9672/lib/NGT/Thread.h#L191 "Update candidate: waitForFull()") of the function “[`JobQueue::wait`](https://github.com/yahoojapan/NGT/blob/985ffad43c8057f37ef95c65caddaf75fe3b9672/lib/NGT/Thread.h#L106)”.
Would you like to reuse anything from my message on the topic “[spurious wakeup](https://groups.google.com/d/msg/comp.programming.threads/Gpe38hgZlsQ/1_1SRoCZgrsJ)”?

**Comment by dmyzk** [comment]
Thank you for your suggestion!

**Comment by elfring** [comment]
How do you think about to reconsider the implementation of the function “[OutputJobQueue::waitForFull](https://github.com/yahoojapan/NGT/blob/6617e448294afabeb6beebd7f633e4aafa98f3b8/lib/NGT/Thread.h#L191 "Update candidate")”?
