### ISSUE TITLE
inner product distance support?

### ISSUE THREAD

**Issue by zhaojinzhou** [yahoojapan/NGT#55]
inner product distance support?

**Comment by zhaojinzhou** [comment]
It seems there is support only for cosine distance？
what's the differences between **cosine distance** and **normalized cosine distance**?

**Comment by zhaojinzhou** [comment]
I do think the FAISS lib supports only inner product rather than cosine distance is reasonable.
Because if inner product distance is supported, then vectors to be indexed can be handled offline, people can handwrite a process to standardize the indexed vectors and the query vector to get cosine distance. 
But, if only cosine distance supported, you can never get a inner product distance.

**Comment by masajiro** [comment]
NGT does not support inner product below which is not a distance function,
<img src="https://latex.codecogs.com/gif.latex?\sum_{i=1}^{n}x_iy_i">
because NGT is a metric-based indexing method. Isn't the inner product **distance** you wrote this one above?

Although NGT supports cosine similarity which is also not a distance function, correctly NGT  supports pseudo cosine similarity below instead of exact cosine similarity.
<img src="https://latex.codecogs.com/gif.latex?1-\frac{X\cdot&space;Y}{\left&space;\|&space;X&space;\right&space;\|\left&space;\|&space;Y&space;\right&space;\|}" title="1-\frac{X\cdot Y}{\left \| X \right \|\left \| Y \right \|}" />

When you specify normalized cosine similarity, stored vectors are normalized for each magnitude to be 1 before indexing. It means that the actual stored vectors are different from your specified vectors.

[Supported distances](https://github.com/yahoojapan/NGT/wiki/Command-Quick-Reference#create)

**Comment by zhaojinzhou** [comment]
> NGT does not support inner product below which is not a distance function,
> ![](https://camo.githubusercontent.com/2fcada9f98b6dfb24d18923e247cf5ec637259de/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f5c73756d5f7b693d317d5e7b6e7d785f69795f69)
> because NGT is a metric-based indexing method. Isn't the inner product **distance** you wrote this one above?
> 
> Although NGT supports cosine similarity which is also not a distance function, correctly NGT supports pseudo cosine similarity below instead of exact cosine similarity.
> ![](https://camo.githubusercontent.com/1cdd046d2c807b2a6ae6e3b884802defa70013ec/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f312d5c667261637b585c63646f742673706163653b597d7b5c6c6566742673706163653b5c7c2673706163653b582673706163653b5c72696768742673706163653b5c7c5c6c6566742673706163653b5c7c2673706163653b592673706163653b5c72696768742673706163653b5c7c7d)
> 
> When you specify normalized cosine similarity, stored vectors are normalized for each magnitude to be 1 before indexing. It means that the actual stored vectors are different from your specified vectors.
> 
> [Supported distances](https://github.com/yahoojapan/NGT/wiki/Command-Quick-Reference#create)

Well, actually, "inner product"(also known as "dot product")  is a distance function。 [google Similarity Measures](https://developers.google.com/machine-learning/recommendation/overview/candidate-generation#similarity-measures)

We think it contains more information than cosine distance. We are using this kind of distance in our recommendation system, and it works well. 

I'm a engineer rather than an algorithm expert.
And I wonder if any basic theory in this algorithm prevents it from being applied to dot product distance?

Or this algorithm  can be applied to any kind of distance if you want ?  I mean after a lot of coding job.

**Comment by masajiro** [comment]
According to [the definition of a distance function](https://en.wikipedia.org/wiki/Metric_(mathematics)#Definition), inner product is not a distance function but a similarity measure. NGT is based on 1 - 4. Although 4 is not indispensable, functions that doesn't meet 4 reduce the accuracy. "inner product distance" you described looks like "maximum inner product search". If so, It is not nearest neighbor search NGT provides.

While consine similaity just represents angle of vectors, L1 or L2 represents more information than cosine similarity. However, I am not sure it works well.

**Comment by zhaojinzhou** [comment]
> According to [the definition of a distance function](https://en.wikipedia.org/wiki/Metric_(mathematics)#Definition), inner product is not a distance function but a similarity measure. NGT is based on 1 - 4. Although 4 is not indispensable, functions that doesn't meet 4 reduce the accuracy. "inner product distance" you described looks like "maximum inner product search". If so, It is not nearest neighbor search NGT provides.
> 
> While consine similaity just represents angle of vectors, L1 or L2 represents more information than cosine similarity. However, I am not sure it works well.

THANK YOU A LOT

**Comment by masajiro** [comment]
Since the maximum inner product search can be transformed to the nearest neighbor search according to https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/XboxInnerProduct.pdf, I will consider implementing this. But I think it is not easy.

**Comment by zhaojinzhou** [comment]
> Since the maximum inner product search can be transformed to the nearest neighbor search according to https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/XboxInnerProduct.pdf, I will consider implementing this. But I think it is not easy.


We used another method.   We ensure all the vector , to be indexed, has the same lenght.   Cos(x,y)  = x*y/|x|*|y|, where x is the query, y is the vectors to be searched, and |x|*|y| is a const number。The comparison between Inner products can be represented by cos distance.

However, the performance  deteriorated severely.

**Comment by masajiro** [comment]
Thank you for the helpful advice.
