### ISSUE TITLE
macOS install

### ISSUE THREAD

**Issue by asparamancer** [yahoojapan/NGT#57]
I'm following the install instructions for macos, but when I get to `make ` it returns:

```
[  2%] Built target versiondef
[  5%] Building CXX object lib/NGT/CMakeFiles/ngtstatic.dir/ArrayFile.cpp.o
clang: warning: -lrt: 'linker' input unused [-Wunused-command-line-argument]
clang: error: unsupported option '-fopenmp'
make[2]: *** [lib/NGT/CMakeFiles/ngtstatic.dir/ArrayFile.cpp.o] Error 1
make[1]: *** [lib/NGT/CMakeFiles/ngtstatic.dir/all] Error 2
make: *** [all] Error 2
```

I've tried recompiling GCC-9.2

**Comment by masajiro** [comment]
It looks like you use clang instead of gcc (g++), probably because the environment variables CXX and CC are not set properly. After removing the directory "build", you may want to follow [the steps](https://github.com/yahoojapan/NGT#on-macos-using-homebrew) again.

**Comment by masajiro** [comment]
Clang is now available by PR #58. Thanks @ankane. You might need to install openmp as follows and upgrade cmake.
```
brew install libomp
```

**Comment by asparamancer** [comment]
Thanks, will take a look at the clang one. But macOS Catalina appears to have a simlink to clang from `CXX=/usr/local/bin/g++` and `CC=/usr/local/bin/gcc`

I set them to `CXX=/usr/local/Cellar/gcc/9.2.0_3/bin/g++-9` and `CC=/usr/local/Cellar/gcc/9.2.0_3/bin/gcc-9` and it worked then

**Comment by ankane** [comment]
I think the GCC instructions should be:

```sh
export CXX=/usr/local/bin/g++-9
export CC=/usr/local/bin/gcc-9
```

**Comment by asparamancer** [comment]
Yep that would be better @ankane , thank you!
