### ISSUE TITLE
About optimizer

### ISSUE THREAD

**Issue by zzltt** [yahoojapan/NGT#61]
can index be optimized by multithread？

**Comment by masajiro** [comment]
If your question means whether you can simultaneously optimize multiple indexes with different parameters from a single index by multiple threads, yes you can with multiple instances of “Optimizer”. However, the optimization measures actual search times in a part of the processing. Therefore, when you simultaneously optimize multiple indexes, the parameters of the optimized indexes might not be the best.

**Comment by zzltt** [comment]
I didn't make myself clear. There are 100k data. I covert anng to onng , the graph optimizer spend too much time. So i want to know whether optimiezer could be  accelerated by multithread. And i don't know optimizer still spend a long time  if i only append ten elements to a onng.

**Comment by masajiro** [comment]
The most part of optimizer is processed by multithreads. Optimizer consists of adjusting the incoming and outgoing edges, removing shortcut edges, adjusting search parameters and prefetch parameters. Although I am not sure whether the time is loner than I expect, if so, adjusting search parameters might be slow for 100K objects. This adjustment measures actual search times with a single thread. When the number of objects is not enough or other processes are running on the computer at the same time, the search times fluctuate. As the result, it takes more time to adjust search parameters. 100K objects is a little fewer than I expect.

Optimizer always optimize all of a graph, even if you append only ten objects to a graph. Once you have already built ONNG, optimization after 10 insertions is not effective for search performance.

**Comment by GuodongTian** [comment]
> The most part of optimizer is processed by multithreads. Optimizer consists of adjusting the incoming and outgoing edges, removing shortcut edges, adjusting search parameters and prefetch parameters. Although I am not sure whether the time is loner than I expect, if so, adjusting search parameters might be slow for 100K objects. This adjustment measures actual search times with a single thread. When the number of objects is not enough or other processes are running on the computer at the same time, the search times fluctuate. As the result, it takes more time to adjust search parameters. 100K objects is a little fewer than I expect.
> 
> Optimizer always optimize all of a graph, even if you append only ten objects to a graph. Once you have already built ONNG, optimization after 10 insertions is not effective for search performance.

Thanks for your clear explaintation, which also answered the question in my mind.
