### ISSUE TITLE
Invalid ids for objects

### ISSUE THREAD

**Issue by joshcabral** [yahoojapan/NGT#62]
When using index.search or index.get_object, it sometimes returns object ids that are larger than the total length of the inserted data. When I try to delete these object Ids, I recieve an error saying that there objects are not in the index.

If I comment the remove function and uncomment the get_object, the code runs without error.
NGT-1.9.0
Python 3.8.2
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-31-1c1416c58265> in <module>
      2 for i in tqdm(range(3606235, 3607995)):
----> 3     index.remove(i)
      4 #     index.get_object(i)
      5 index.save()

RuntimeError: /home/jupyter/NGT-1.9.0/lib/NGT/Index.h:1622: remove:: cannot remove from tree. id=3606236 /home/jupyter/NGT-1.9.0/lib/NGT/Tree.h:191: VpTree::remove: Inner error. Cannot remove object. leafNode=203725:/home/jupyter/NGT-1.9.0/lib/NGT/Node.cpp:260: VpTree::Leaf::remove: Cannot find the specified object. ID=3606236,0 idx=80 If the same objects were inserted into the index, ignore this message.

**Comment by masajiro** [comment]
Do you use ONNG which is optimized from ANNG (default graph type)? When you use ONNG, removing objects causes inconsistency between the graph index and object repository including the tree index.

**Comment by joshcabral** [comment]
I was receiving the invalid indices before I tried to remove them from the graph. I tried to remove them because there are not part of the training set and they are values larger than the total dataset

**Comment by masajiro** [comment]
If you got the index which has invalid object IDs only by inserting objects, I have no idea because I have not had such problems. Could you send the invalid index or your program to build the index, if possible?

**Comment by joshcabral** [comment]
Do you need the entire folder or is there a specific file which contains the necessary information. The entire folder is bigger than 60gb.  Below is the code that ran. There are 3606235 rows in the dataset and approx 200,000 in each batch 
```
import numpy as np
import pickle
import ngtpy
from tqdm import tqdm
from multiprocessing import cpu_count
NUM_CPUS = cpu_count()

dim = 4007

index_path = '/mnt/disks/big/loocv-cosine-dim-4007.anng'
ngtpy.create(index_path, dim, distance_type='Cosine')
index = ngtpy.Index(index_path, ) # open the index

for i in tqdm(range(18)):
    
    # Load data sets
    with open('/mnt/disks/big/queryresults%s.pickle'%i, 'rb') as handle:
        result = pickle.load(handle)
    x, y1, y2, y3, y4, y5 = zip(*result)

    n = len(y1)
    x = np.array(x).reshape((n, dim))
    index.batch_insert(x, num_threads=NUM_CPUS)

    del x, y1, y2, y3, y4, y5

index.build_index(num_threads=NUM_CPUS) # build the index
index.save()

```
<img width="422" alt="Screen Shot 2020-04-23 at 12 12 52 AM" src="https://user-images.githubusercontent.com/54961111/80061538-2e7db400-84f7-11ea-9f1d-2527be5904d2.png">

**Comment by masajiro** [comment]
The entire folder is better. Can you put it anywhere where I can download?  Perhaps I can accept more than 60GB.
