### ISSUE TITLE
Jaccard distance comparator doesn't get initialized if `NGT_SHARED_MEMORY_ALLOCATOR=ON`

### ISSUE THREAD

**Issue by mihajenko** [yahoojapan/NGT#65]
It should be initialized here:

https://github.com/yahoojapan/NGT/blob/f9fcbeac00e3c527e129c5a59e2e86edeb207713/lib/NGT/ObjectSpaceRepository.h#L279

**Comment by masajiro** [comment]
Thank you for your suggestion. I have released v1.11.3 which fixes this problem.
