### ISSUE TITLE
SIGSEGV when removing an object before commit

### ISSUE THREAD

**Issue by lerouxrgd** [yahoojapan/NGT#67]
Hello, I am currently writing [Rust wrappers](https://github.com/lerouxrgd/ngt-rs) for NGT, inspired by Python/Go/Ruby bindings.

During a test where I do the following:
- Create new empty index
- Insert an object
- Remove it --> This will SIGSEGV

Here is the backtrace with gdb:

```
Program received signal SIGSEGV, Segmentation fault.
std::_Bit_reference::operator= (this=0x7fffffff54f0, __x=true) at /usr/include/c++/9.3.0/bits/stl_bvector.h:93
93              *_M_p |= _M_mask;
(gdb) bt
#0  std::_Bit_reference::operator= (this=0x7fffffff54f0, __x=true) at /usr/include/c++/9.3.0/bits/stl_bvector.h:93
#1  0x00007ffff7f15bab in NGT::NeighborhoodGraph::setupSeeds (this=0x555555ce3198, sc=..., seeds=..., results=std::priority_queue wrapping: std::vector of length 1, capacity 1 = {...}, 
    unchecked=std::priority_queue wrapping: std::vector of length 0, capacity 0, distanceChecked=...) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Graph.cpp:313
#2  0x00007ffff7f15f26 in NGT::NeighborhoodGraph::search (this=0x555555ce3198, sc=..., seeds=...) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Graph.cpp:473
#3  0x00007ffff7f3732b in NGT::GraphIndex::search (this=0x555555ce3130, sc=..., seeds=...) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Index.h:1117
#4  0x00007ffff7f38ebe in NGT::GraphAndTreeIndex::remove (this=0x555555ce3130, id=3, force=false) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Index.h:1368
#5  0x00007ffff7ec30cc in NGT::Index::remove (this=0x555555ce5960, id=3, force=false) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Index.h:445
#6  0x00007ffff7eda05e in ngt_remove_index (index=0x555555ce5960, id=3, error=0x555555ce3100) at /home/raru/dev/workspaces/rust/ngt-rs/ngt-sys/NGT/lib/NGT/Capi.cpp:622
#7  0x000055555575b46e in ngt::index::Index::remove (self=0x555555ce3988, id=3) at /home/raru/dev/workspaces/rust/ngt-rs/src/index.rs:241
```

It starts when I call [ngt_remove_index](https://github.com/lerouxrgd/ngt-rs/blob/dd031783ad5b6f22a6a8ddd917899c238aeb5681/src/index.rs#L241). I am using NGT version `1.11.2`.

Is it because we should not try to insert and delete the same object before building an index ?
In which case, would it be possible to get an error instead of SIGSEGV ?
I think this could be less surprising.

**Comment by masajiro** [comment]
Thank you for your information. I have released v1.11.4 which fixes the bug.

**Comment by masajiro** [comment]
@lerouxrgd 
Thank you for writing Rust  wrappers for NGT! May I set a link to your [repository](https://github.com/lerouxrgd/ngt-rs) in the NGT repository?

**Comment by lerouxrgd** [comment]
Thank you for fixing the issue !

Sure please go ahead and add a link to my repository! I just published it on [crates.io](https://crates.io/crates/ngt) so now it is fully usable for Rust users.
