### ISSUE TITLE
InnerProduct

### ISSUE THREAD

**Issue by WaterElapse** [yahoojapan/NGT#70]
Hello,
I have a question,  does NGT support InnerProduct as distance function?
I dont see IP function when use float as datatype.
If it does support IP, have you test the performance using IP as distance function? Compared to Hnsw?

**Comment by masajiro** [comment]
Hello,
I think that you mean maximum inner product search (MIPS). NGT does not support MIPS.
#55 might be helpful.

**Comment by WaterElapse** [comment]
thanks a lot
