### ISSUE TITLE
Broken links in wiki page

### ISSUE THREAD

**Issue by jeongukjae** [yahoojapan/NGT#72]
https://github.com/yahoojapan/NGT/wiki/Graph-Types#anng

> Since it is difficult to adjust these parameters and coefficients above to fit your dataset, there are optimization functions (Command/Python/Cpp) to automatically optimize these parameters.

Links(Python, Cpp) in above paragraph are broken.

**Comment by masajiro** [comment]
Thanks! I updated the links.

**Comment by jeongukjae** [comment]
@masajiro Nice!! :+1:
