### ISSUE TITLE
Using an index built on a 64 bit Linux machine on a 32 bit machine and vice-versa

### ISSUE THREAD

**Issue by OrkhanHI** [yahoojapan/NGT#76]
I have compiled NGT for armeabi-v7a using Android NDK.

I first create an index on a 64 bit linux system using the Python binding.

I then copy the four files in the index folder (grp, obj, prf, tre) to an index folder on Android and try to open the index.

If my Android system is arm64-v8a, then I can open the index successfully on Android.

However, if I try to open the index on a 32 bit Android system, I get a memory allocation crash on trying to open the index.

Similarly, if I create the index on a 32 bit system and then copy the files over to a 64 bit system, I get the same `std::bad_alloc`

Is there any way that the same index (the four files) can work on both 32 bit and 64 bit systems?

Perhaps the property file should store the architecture of the system and then the index should be loaded accordingly.

I really need a way of sharing the index between 32bit and 64 bit systems.

To be clear. NGT on its own (compiled as 32 bit or 64 bit) works on its own on 32 bit and 64 bit systems.

The problem is to use the saved index files from 32 bit on a 64 bit system or vice-versa.

A workaround is to rebuild the index while exchanging the data. But that is very expensive. It would be great to be able to read the index from a 32 bit NGT installation on a 64 bit NGT installation and vice versa.

**Comment by masajiro** [comment]
So far I did not pay attention to compatibility between 64 bits and 32 bits at all. I will look into the problem in the near future, because I have no time right now. At this moment, using the export and import which you found is the best way to use NGT indexes between them.

**Comment by OrkhanHI** [comment]
Hi Masajiro,

Could you please publish this on Pypi when you get a chance, so we dont need to built it from the source every time?


Thank you in advance.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by masajiro** [comment]
Hi Hasanli.
I have just released the latest NGT pypi packages for Linux and macOS. However, how to use the import might be a little confusing.

**Comment by OrkhanHI** [comment]
Thanks @masajiro. Closing this issue.
