### ISSUE TITLE
Can I install this on Windows 10?

### ISSUE THREAD

**Issue by zubairahmed-ai** [yahoojapan/NGT#78]
As above I am using Win OS, can you please let me know how to install it?

**Comment by masajiro** [comment]
Unfortunately, currently NGT cannot be installed to Windows OS.
Please refer to #42.

**Comment by zubair-ahmed-ai** [comment]
That's sad, I came to NGT after trying [Annoy](https://github.com/spotify/annoy) was really hoping that this would work. I'll try this on a Linux OS
