### ISSUE TITLE
Error in make install step

### ISSUE THREAD

**Issue by zubairahmed-ai** [yahoojapan/NGT#86]
I am on Ubuntu 18 OS and everything went fine until the `make install` step.

I am getting the below error and not sure why.

```
[100%] Built target jaccard-sparse
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libngt.so.1.12.1
CMake Error at lib/NGT/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/.../NGT-1.12.1/build/lib/NGT/libngt.so.1.12.1"
  to "/usr/local/lib/libngt.so.1.12.1".
Call Stack (most recent call first):
  lib/cmake_install.cmake:42 (include)
  cmake_install.cmake:42 (include)


Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1

```

**Comment by masajiro** [comment]
Do you have permission to install NGT to /usr/local?
Another option is using [PYPI package](https://github.com/yahoojapan/NGT/wiki/Python-Quick-Start#installation).

**Comment by zubairahmed-ai** [comment]
Ha! just like that after seeing your message that it could be permission issue I tried `sudo make install` and it worked before this page even open, thanks a bunch! Now I am going to try your other example
