### ISSUE TITLE
Python library import error

### ISSUE THREAD

**Issue by fychiu** [yahoojapan/NGT#9]
Hi I meet a problem when using python library. The below is the error message. Do I have to build from scratch before I install the python library by pip? 
(Just in case I forgot to install any dependency.)
```
>>> from ngt import base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ngt/base.py", line 42, in <module>
    class Index(object):
  File "ngt/base.py", line 88, in Index
    __ngt.ngt_open_index.argtypes = [c_char_p, c_void_p]
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: ngt_open_index
```

**Comment by masajiro** [comment]
You are right. You have to build and install the NGT library before installing the python NGT.
The error message means that the python NGT cannot load the NGT library.

**Comment by fychiu** [comment]
Problem solved.
Also, in your guidance, the last line: "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64", I removed "64" to be "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib".
Not sure whether this is an issue for others.
Anyway, thanks a lot.
