### ISSUE TITLE
Add new NGTQG to C API

### ISSUE THREAD

**Issue by lerouxrgd** [yahoojapan/NGT#92]
Would it be possible to add latest NGTQG to the C API ?
It would be then possible for wrappers to stay up to date.

**Comment by masajiro** [comment]
Thank you for your request, but give me some time.

**Comment by lerouxrgd** [comment]
Sure, there is no hurry, thank you very much !

**Comment by masajiro** [comment]
Sorry for the late response. I have pushed the branch [ngtqg-capi ](https://github.com/yahoojapan/NGT/tree/ngtqg-capi) including the ngtqg C API source codes below.
[Capi.h](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/lib/NGT/NGTQ/Capi.h)
[Capi.cpp](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/lib/NGT/NGTQ/Capi.cpp)
Please refer an [example code](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/lib/NGT/NGTQ/Capi.h#L18-L86) using the APIs in Capi.h. The [ngtqg_quantize](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/lib/NGT/NGTQ/Capi.h#L29) and [ngtqg_search_index](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/lib/NGT/NGTQ/Capi.h#L75) are almost the same as the [quantize](https://github.com/yahoojapan/NGT/tree/ngtqg-capi/bin/ngtqg#quantize) and [search](https://github.com/yahoojapan/NGT/tree/ngtqg-capi/bin/ngtqg#search) of the [ngtqg](https://github.com/yahoojapan/NGT/blob/ngtqg-capi/bin/ngtqg/README.md) command, respectively. If there are no problems with the C APIs, I will merge them into the master branch.

**Comment by lerouxrgd** [comment]
Thank you for the C API and the example, it is very useful. I managed to use the C API correctly and here are my findings:
- Would it be possible to have a function to retrieve an object from a quantized index ? Something like `ngt_get_object_as_integer` and `ngt_get_object_as_float` in the regular index case.
- How to check the result of `ngtqg_quantize` ? Would it be possible to return true/false so that we know whether we have to check the `NGTError` ?
- There is a typo in `NGTQGQuantizationPrameters` -> NGTQGQuantizationP**a**rameters

**Comment by lerouxrgd** [comment]
Also on a similar topic, I noticed that `ngt_set_property_distance_type_sparse_jaccard` is missing in the regular C API.

**Comment by masajiro** [comment]
Thank you for your comments. I have released [NGT v1.13.7](https://github.com/yahoojapan/NGT/releases/tag/v1.13.7) with NGTQG C APIs.
> - Would it be possible to have a function to retrieve an object from a quantized index ? Something like ```ngt_get_object_as_integer``` and ```ngt_get_object_as_float``` in the regular index case.

You can also use ```ngt_get_object_as_float``` for the quantized indexes like [this](https://github.com/yahoojapan/NGT/blob/master/lib/NGT/NGTQ/Capi.h#L86).

> -  How to check the result of ```ngtqg_quantize``` ? Would it be possible to return true/false so that we know whether we have to check the ```NGTError``` ?

I modified ```ngtqg_quantize()``` to return its status.

> - There is a typo in NGTQGQuantizationPrameters -> NGTQGQuantizationParameters

Thanks.

> Also on a similar topic, I noticed that ngt_set_property_distance_type_sparse_jaccard is missing in the regular C API.

At this moment I cannot afford to deal with the sparse jaccard which is significantly different from other distances in terms of implementation.

**Comment by lerouxrgd** [comment]
Thank you for the fixes, everything looks good !

Just one last question, NGTQGIndex is not compatible with feature NGT_SHARED_MEMORY_ALLOCATOR ? I tried to test it and got SIGABRT.

**Comment by masajiro** [comment]
Thank you for reviewing.
I am wondering whether I should support NGT_SHARED_MEMORY_ALLOCATOR for NGTQG, because this spoils the fastest NGTQG index of the NGT indexes.

**Comment by lerouxrgd** [comment]
I see, indeed it is better not to spoil performances. I found the NGT_SHARED_MEMORY_ALLOCATOR very convenient so I just wanted to check it with NGTQG Index.

**Comment by lerouxrgd** [comment]
Anyway as long as C API is concerned everything is fine, thank you again for adding this !
