### ISSUE TITLE
what is the latest release

### ISSUE THREAD

**Issue by chenrui333** [yahoojapan/NGT#94]
👋  I have a QQ about the release tag. 

I saw the latest release `1.13.4` got marked as `pre release`, but the latest release was tagged on `1.12.3`, so raising this issue asking what is the latest release (is it `1.13.3` or `1.12.3`).

Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/71161

**Comment by masajiro** [comment]
At this moment, the latest release is V1.12.3. V1.13.4 is just the pre-release. Since I found some bugs in from V1.13.0 to V1.13.3, I did not mark them as release or pre-release. V1.13.4 will be the latest release soon.

**Comment by chenrui333** [comment]
Thanks!
