### ISSUE TITLE
Does it support online vector deletion and insertion?

### ISSUE THREAD

**Issue by shuitai** [yahoojapan/NGT#95]
Does it support online vector deletion and insertion?
like https://github.com/microsoft/SPTAG

**Comment by masajiro** [comment]
You can delete and insert vectors for the default graph ANNG without rebuilding the index. However, once you build ONNG from ANNG, you can not delete but insert vectors. Since NGT has no locking, you have to exclusively control multiple deletions and insertions by multiple threads.
