### ISSUE TITLE
Python 3.9 Wheel

### ISSUE THREAD

**Issue by ankane** [yahoojapan/NGT#96]
Hi, thanks for this great library. I was trying to install NGT with Python 3.9 and noticed there [isn't a wheel](https://pypi.org/project/ngt/#files) for Python 3.9 yet.

```txt
pip3 install ngt
ERROR: Could not find a version that satisfies the requirement ngt
ERROR: No matching distribution found for ngt
```

Is it possible to publish one?

**Comment by masajiro** [comment]
I added NGT v1.12.2 for python 3.9.
https://pypi.org/project/ngt/1.12.2/#files

**Comment by ankane** [comment]
Working great, thanks @masajiro!
