### ISSUE TITLE
User-defined filters - as seen in Vald

### ISSUE THREAD

**Issue by zygm0nt** [yahoojapan/NGT#97]
Hi

I've looked into Vald and that's how I reached NGT. One of the features I look for is filtering of a given vector set. Vald boasts it can do it (https://vald.vdaas.org/docs/usecase/usage-example/ - 'Advanced use cases' section). Is it possible to do that filtering with bare NGT?

**Comment by masajiro** [comment]
Hi. I am not so sure what the user-defined filters are, however, NGT does not have any filters.

**Comment by zygm0nt** [comment]
Ok, I see. I'll try to go through `vald` sources to see how this is implemented on top of `NGT`.
